.dockerignore, Dockerfile, Makefile, docker-entrypoint.sh
=> Add docker stuff to make deployable

reload_app/app.py
Using `click` felt weird.
Adding this for Assistant search.
=> Adding search as a valid event type

Dockerfile, Makefile, reload_app/app.py, reload_app/raven_client.py, reload_app/tests.py, requirements.txt
Have some weird cases of user ids ending with ';'. There are some SQL injection attacks too :)
=> Validate user_id in reload server

reload_app/app.py
=> Whitelist issue.search event type

reload_app/app.py
Add sourcemap.sourcemap_error to whitelist
cc @ehfeng @denamwangi
=> Add sourcemap.sourcemap_error to whitelist

reload_app/app.py
This will make it a little easier to debug in dev
=> feat: Adding more descriptive error messages

reload_app/app.py
These will be used to track user interaction with the onboarding wizard
=> feat: Add onboarding wizard events to allowed events

reload_app/app.py
... for command palette
Remember to update...
=> Add 'omnisearch.open', 'omnisearch.select'

reload_app/app.py
Adds event for when users click upgrade button in sso paywall experiment.
See this [PR](https://github.com/getsentry/sentry/pull/8836) for experiment details.
=> feat: Add sso paywall click event

reload_app/app.py
Whitelist the create sample event action by users - related [PR](https://github.com/getsentry/sentry/pull/9015)
=> feat: Add sample event analytics to whitelist

reload_app/app.py
This allows us to see where orgs send sample events from e.g. dashboard, signup flow
=> chore: Add source for sample event analytics

reload_app/app.py
Implemented in this [PR](https://github.com/getsentry/sentry-docs/pull/266)
=> add docs feedback event to whitelist

.dockerignore, cloudbuild.yaml
=> Add cloudbuild.yaml

reload_app/app.py
related to [getsentry-PR](https://github.com/getsentry/getsentry/pull/2129)
=> add sso paywall viewed event

reload_app/app.py
Event being logged in https://github.com/getsentry/sentry/pull/9520
=> Add event for docs/FAQ search

reload_app/events.py
Add analytics to capture progression through each card in the releases tab
=> feat: Add releases tab card clicks event

reload_app/events.py
related to [sentry pr](https://github.com/getsentry/sentry/pull/10113)
=> chore: Add releases tab viewed event to whitelist

reload_app/events.py
related: [sentry PR](https://github.com/getsentry/sentry/pull/10125) and [getsentry PR](https://github.com/getsentry/getsentry/pull/2280)
=> chore(experiments): SSO experiments cleanup

reload_app/events.py
Track when users click "Use UTC" and when they change start/end times
=> feat(): Add 'dateselector' events

reload_app/events.py
Adds events for feature upgrade flows.
=> feat: Add feature upgrade events

reload_app/events.py
This is for https://github.com/getsentry/getsentry/pull/2353
=> feat: Add membership_limit.upgrade_clicked

reload_app/metrics/__init__.py
Should be `app.api.request-error`
=> fix(metrics): Fix `app.api.request-fail` metric name

reload_app/app.py, reload_app/tests.py, requirements.txt
=> feat(metrics): Parse user agent for browser and os

reload_app/metrics/__init__.py
For measuring when an AsyncComponent renders + completes API requests --> updates.
This is required for https://github.com/getsentry/sentry/pull/10922
=> feat(metrics): Add `app.component.async-component`

reload_app/events.py
Adds an event for when the survey is viewed and one with the enclosed data when the survey is submitted
related to [getsentry-PR](https://github.com/getsentry/getsentry/pull/2417/files)
=> whitelist onboarding events

reload_app/events.py
This tracks how much the stream search sidebar gets used
=> event(ui): Issue stream sidebar clicked

reload_app/events.py
related to https://github.com/getsentry/getsentry/pull/2455
=> Whitelist request another trial

reload_app/events.py
related to https://github.com/getsentry/getsentry/pull/2456
=> Whitelist contact sales event

reload_app/events.py
Whitelist a few more analytics events related to the trial v upgrade cta experiment
=> Add more upgrade or trial button viewed events

reload_app/events.py
Related to https://github.com/getsentry/getsentry/pull/2574
=> Add plan to all events for trialupgrade experiment

reload_app/events.py
Required for https://github.com/getsentry/sentry/pull/11896/files
=> feat(sentry10): Add events for project/env selector

reload_app/events.py
Analytics for business landing entrypoint clicks ("try business" in sidebar and power icons)
related to https://github.com/getsentry/getsentry/pull/2624
=> Add business landing entry point clicks

reload_app/events.py
related to https://github.com/getsentry/getsentry/pull/2693
- Takes out try business clicks
- Fixes typo in power icon clicks
=> chore: Update Try Business analytics

reload_app/events.py
Appear to have issues with adding an attribute with the name type. Fixed the issue by naming the field search_type instead.
=> fix(analytics): Saved Search Analytics

.dockerignore, .travis.yml, Dockerfile, Makefile, pyproject.toml, reload_app/__init__.py, reload_app/app.py, reload_app/events.py, reload_app/geo.py, reload_app/metrics/__init__.py, reload_app/metrics/base.py, reload_app/metrics/dogstatsd.py, reload_app/router.py, reload_app/tests.py, reload_app/utils.py, reload_app/worker.py, requirements-test.txt, requirements.txt, run.py, setup.cfg
Also formatted with `black` which can be done with `make format` in the
future.
=> Update to Python 3.7

reload_app/events.py
Required for: https://github.com/getsentry/sentry/pull/13108
=> feat(onboarding): Add onboarding_v2 events

reload_app/events.py
Trying to make the different event types more clear
=> ref: Separate event types with comments

reload_app/events.py
Required after https://github.com/getsentry/sentry/pull/14066
=> Remove old onboarding events

reload_app/events.py
-------
Corresponding PR at https://github.com/getsentry/sentry/pull/15373
=> feat(discover2): Add some events to track for Discover 2

reload_app/events.py
=> feat(analytics): Add onboarding support link tracking

reload_app/events.py
Sentry PR: https://github.com/getsentry/sentry/pull/16369
=> feat(ui): adds analytics events for sidebar item clicked

reload_app/events.py
Tied to changes in: https://github.com/getsentry/sentry/pull/16419
=> feat(integrations): add more fields to integrations.install_modal_opened event

reload_app/events.py
PR to match: https://github.com/getsentry/sentry/pull/16508
=> feat(integrations): adds more integration events

reload_app/events.py
Matches with: https://github.com/getsentry/sentry/pull/16588
=> adds integration status for integration events

reload_app/events.py
Goes with PR: https://github.com/getsentry/sentry/pull/16504
=> feat(analytics) adds source_type and result_type to select events

reload_app/events.py
Usage: https://github.com/getsentry/sentry/pull/17035
Part of: https://www.notion.so/sentry/Default-Alert-Options-450bbbc6f83b4ba29350fb9a59cf5746
=> feat(analytics): Add alert rule creation event

reload_app/events.py
Usage: getsentry/sentry#17035
Part of: https://www.notion.so/sentry/Default-Alert-Options-450bbbc6f83b4ba29350fb9a59cf5746
=> feat(analytics): Add new project visit event

reload_app/events.py
Fixes: [RELOAD-1J](https://sentry.io/share/issue/5354b0cdb3794abe82834dfa946f90f3/)
=> fix(onboarding): Convert todo_id to string to match sentry

reload_app/events.py
* Alert Details
* Alert Stream
* New Alert Rule
=> feat(events): Add events for Alert-related pageviews

reload_app/events.py
Add a new event type.
Associated PR in GetSentry: https://github.com/getsentry/getsentry/pull/3737
Associated PR in Sentry: https://github.com/getsentry/sentry/pull/18119
=> feat(Events): Add integrations.directory_category_selected to events

reload_app/events.py
Needed for the new trial ended modal.
=> feat: Add trial_ended_notice events

reload_app/events.py
=> feat: Add alert stream documentation clicked events

reload_app/events.py
=> feat(performance-views) Add metrics for new performance tour

reload_app/events.py
* Adds first_transaction_received
* Updates first_event_received to add a project (which was already sent)
Ref: https://github.com/getsentry/sentry/pull/20291
=> Add event to track onboarding transaction step

reload_app/events.py
=> feat(discover) Add discover tour events

reload_app/events.py
=> feat(analytics): Add sample event failed

reload_app/events.py
=> feat(perf-views) Add key transaction event

reload_app/events.py
=> feat(analytics): Add upgrade events

reload_app/events.py
=> feat(analytics): Add upgrade plan attributes

reload_app/events.py
Adds some events for the new landing page v2, to make sure the new dropdowns are accurate and useful.
=> feat(perf): Add events for new landing page

reload_app/events.py
=> feat(workflow): Allow inbox tab clicked event

reload_app/events.py
=> feat(analytics): Add checkout slider events

reload_app/events.py
=> feat(workflow): Add issue stream click/assigned events

reload_app/events.py
- Capture when a user looks at a certain alert type (e.g. 'throughput', 'trans_duration', 'lcp')
- Capture when a user makes a selection for a certain alert type
https://github.com/getsentry/sentry/pull/25771
=> feat(alert): Capture metrics for alert wizard (WOR-865)

reload_app/events.py
Add events to capture analytics for dashboard
manager page.
=> feat(dashboards): Add dashboard manager events

reload_app/events.py
These will be used in https://github.com/getsentry/getsentry/pull/5530/
=> feat: Capture metrics for global messages

reload_app/events.py
https://github.com/getsentry/sentry/pull/27298
=> feat(search): Analytics on operator autocomplete

reload_app/events.py
Added 4 events for the checkout page.
=> Added new checkout events

reload_app/events.py
adds alert_type to `new_alert_rule` and 3 new analytics
=> feat(workflow): Add alert details view event, edit alert rule

reload_app/events.py
Related: https://github.com/getsentry/getsentry/pull/6320
=> feat(growth): Add business landing closed event

reload_app/events.py
This adds an analytic to check if a future button 'Add to Dashboard' has high utility on the landing page
=> feat(perf): Add analytic for potential 'add to dashboard'

reload_app/events.py
Added `widgetType` field to track if the change event is for an issue widget or discover widget
https://github.com/getsentry/sentry/pull/29925
=> feat(dashboards): added widgetType to dashboards_views.add_widget_modal.change event

reload_app/events.py
https://github.com/getsentry/sentry/pull/30270
=> fix(dashboards): Renamed widgetType to widget_type

reload_app/events.py
=> chore(suspect-spans): Add analytics to span tab

reload_app/events.py
Add analytics events to track widget library
usage.
https://github.com/getsentry/sentry/pull/30762
=> chore: Add Widget Library Analytics

reload_app/events.py
- This adds the events for dash templates
=> feat: updating events list for dashboard templates

reload_app/events.py
Corresponding pull request in https://github.com/getsentry/getsentry/pull/7077
=> feat(billing): Add on-demand budget analytics

reload_app/events.py
see https://github.com/getsentry/sentry/pull/32241
=> feat(alerts): Add events for new alert status page

reload_app/events.py
Add event for tracking discover query conditions
Sentry pr https://github.com/getsentry/sentry/pull/32700
=> feat(discover): Add event for tracking discover query conditions

reload_app/events.py
https://github.com/getsentry/sentry/pull/32751
=> feat(workflow): Add `search.display_changed`

reload_app/events.py
see https://github.com/getsentry/sentry/pull/32765
=> feat(workflow): Add `issue_details.action_clicked` and viewed

reload_app/events.py
Add track analytics code for the widget builder
Used in sentry here https://github.com/getsentry/sentry/pull/33168
=> ref(new-widget-builder-experience): Add track analytic code

reload_app/events.py
removed in https://github.com/getsentry/getsentry/pull/7184
=> feat(ui): Remove global notification

reload_app/events.py
used in https://github.com/getsentry/sentry/pull/33654
=> feat(workflow): Issue details older/newer nav

reload_app/events.py
related https://github.com/getsentry/sentry/pull/33774
=> feat(workflow): Add `issue_details.event_json_clicked`

reload_app/events.py
Get some analytics on clicking the pin button
https://github.com/getsentry/sentry/pull/33532
=> feat(page-filters): Analytics on pin button

.github/workflows/ci.yml
added codecov.yml file and included commands for running/uploading coverage reports with codecov for github actions in the workflow .yml
=> integrate codecov

reload_app/events.py
Follow-up of https://github.com/getsentry/sentry/pull/36513
=> ref(sampling): Add analytic code for sampling - [TET-173]

reload_app/events.py
Follow-up of https://github.com/getsentry/sentry/pull/37251
=> ref(sampling): Add analytics code for the specify client rate modal - [TET-279]

reload_app/events.py
see related https://github.com/getsentry/sentry/pull/37562
=> feat(workflow): Track clicks of issues stream realtime feature

reload_app/events.py
Other half of https://github.com/getsentry/sentry/pull/37640
=> feat(issues): Add event for changing the issues stream sort

reload_app/events.py
Finishing up what Jenn started in https://github.com/getsentry/sentry/pull/37742
=> feat(issues): Add new search analytics events

reload_app/events.py
Fixes https://sentry.io/organizations/sentry/issues/2912376661/?project=133215
=> Change dashboard id type

reload_app/events.py
Depends on: https://github.com/getsentry/sentry/pull/38807
=> feat(perf-issues): Add perf issue analytics events

reload_app/events.py
fixes https://getsentry.atlassian.net/browse/WOR-2181
=> feat(ecosystem): Track suspect commit count

reload_app/events.py
related https://github.com/getsentry/sentry/pull/39448
=> feat(ecosystem): Add stacktrace_link_viewed event

reload_app/events.py
https://github.com/getsentry/sentry/pull/39728
=> feat(monitors): Add analytics on page view

reload_app/events.py
https://github.com/getsentry/sentry/pull/40369
=> feat(monitors): Add monitor failed analytics

reload_app/events.py
https://github.com/getsentry/sentry/pull/40871
=> feat(saved-searches): Add event for creating a saved search

reload_app/events.py
Sentry PR: https://github.com/getsentry/sentry/pull/41064
=> feat(analytics): Track project platform on span details expand event

reload_app/events.py
Add a new parameter to match changes in https://github.com/getsentry/sentry/pull/42162
=> chore(perf): Update performance_views.landingv3.widget.switch parameters

reload_app/events.py
https://github.com/getsentry/sentry/pull/42835
=> ref(crons): Add page view empty_state analytic parameter

reload_app/events.py
https://github.com/getsentry/sentry/pull/42847
=> feat(crons): Add cron monitor details page view event

reload_app/events.py
Related Frontend PR: https://github.com/getsentry/sentry/pull/46086
=> feat(analytics): Add analytics event for `IssueCategoryDropdown`

gocd/pipelines/reload.yaml
Committed via https://github.com/asottile/all-repos
=> Update to new k8s deploy script

.github/workflows/ci.yml, Dockerfile, reload_app/tests.py, requirements-test.txt, requirements.txt
Bump a few other versions as well to get this thing building and testing correctly
=> [OPS-172] bump version to address CVE-2024-34069
