getsentry/reload

reload_app/app.py

Linked to this GH [PR](https://github.com/getsentry/sentry/pull/7764) that introduces click tracking for assistant guides.

feat: Add valid event names for assistant guide click tracks

---

reload_app/app.py
reload_app/router.py
reload_app/tests.py

We already had event name validation. This takes it a step further and ensures that for each event only specific fields are accepted, and that they are cast-able to the correct type.

More validation for events

---

reload_app/app.py
reload_app/tests.py

Adding in an extra check just for `events` endpoint (don't care about page, but can add there as well. Will reject if you are sending a different data type than specified in VALID_EVENTS. Not sure if this is too harsh.
conclusion: Sending a sentry warning

feat:Extra type check

---

reload_app/app.py

> We'd like to dive a bit deeper into exactly what issue errors are being seen by users. To that effect, we need a bit more data:
> 1. Change type from `sourcemap.sourcemap_error` to the more generic `issue_error_banner.viewed` (analytics events generally use underscore at sentry)
> 2. Add error message and platform or sdk to event payload
https://getsentry.atlassian.net/browse/SE-77

add more fields and change event name

---

reload_app/app.py

So that they appear as separate Sentry issues and are more actionable.

Customize unexpected field type warning message

---

reload_app/events.py

Added two more click events for when they click the cta and for when they close the bar- whitelisting here.
Related to https://github.com/getsentry/sentry/pull/10408/files

whitelist more releases clicks

---

reload_app/events.py

This is mainly a safety measure. Just in case some random ipad or browser somewhere handles this differently and doest send the project_id I'm collecting in `sample_event.button_viewed`.
Related sentry event: https://sentry.io/sentry/javascript/issues/764141265/

fix: Add safety event for sample event experiment

---

.travis.yml
reload_app/app.py
reload_app/geo.py
reload_app/metrics/__init__.py
reload_app/tests.py
requirements.txt

Hmm I can't find a free db that works with their legacy client which we're using

feat(metrics): Add geo data to metric calls

---

reload_app/events.py

related to https://github.com/getsentry/sentry/pull/11149
Adds the cta to the progress bar viewed events. Can be deduced but this makes it easier

add cta to progress bar viewed events

---

client/ra.js

`.includes` isn't supported well enough, so sentry.io is constantly blowing up on this.

fix: includes -> indexOf for compatibility

---

reload_app/events.py

Add event to track deprecated URLs.
-------
We'll be redirecting users who are consuming deprecated URLs, and they will be redirected to newer URLs. We'd also like to be able track these redirects to ensure we will bake in support for these redirects.
Associated PR at https://github.com/getsentry/sentry/pull/13722
Part of SEN-772

feat(redirect): Add event to track deprecated URLs

---

reload_app/metrics/__init__.py

Added `app.component.perf` as a valid metric so it is tracked and forwarded to data dog. This metric was added by [this pr](https://github.com/getsentry/sentry/pull/14820).
Refs SEN-1058

feat(metrics): Track performance of organization details

---

reload_app/events.py

The project_id is an optional parameter to the `sidebar.item_clicked` event (only passed when you pick a plugin which brings up the project dropdown). The result is that when the value is not provided, we get the following warning:
```
WARNING: Property key "project_id" with invalid value type undefined, ignoring
```
Reload will ignore any event which does not have `project_id` set. Best course is to remove it

fix(analytics): remove project_id from sidebar.item_clicked event

---

reload_app/events.py

User id is redundant as it's automatically logged, thus removing it.

fix(analytics): Remove user id from new project event

---

reload_app/events.py

This is a generic event that should track deprecated/legacy features to see when we can safely remove.

feat(event): Add `deprecated.feature`

---

.gitignore

Our [docs here](https://develop.sentry.dev/environment/#virtual-environment) recommends naming the virtualenv folder as `.venv`

meta(git): Add .venv to .gitignore

---

reload_app/events.py

The other event is capturing whether they are seeing the landing content, which switches them between the beta and non-beta view. This will capture specifically if they are on the new view

feat(perf): Add event for the new landing specifically

---

Dockerfile

Checking against PGP keyservers is flaky and old and busted, just use a checksum. We do this for Sentry here: https://github.com/getsentry/sentry/blob/master/docker/Dockerfile#L20
Also upgrades gosu and tini each a minor version to match what's in Sentry, the changes are trivial.

fix(build): replace PGP check with sha256sum

---

reload_app/app.py

Jira issue: https://getsentry.atlassian.net/browse/OPS-949
Why I want to fix this? Because it is at the top in our Google Error Reporting dashboard, and I'd like to make it cleaner.
Sometimes `data` dictionary contains `dashboard_id` with `None` value. With that, `int(None)` is being executed in try block, giving `TypeError` exception. This PR does not fix the source of `dashboard_id = None` (probably this is right thing to do), but just skips such events from validation.
Should fix these sentry issues:
https://sentry.io/organizations/sentry/issues/1809964681/
https://sentry.io/organizations/sentry/issues/1809964689/

Skip field validation if corresponding data is None

---

reload_app/events.py

This is a temporary event to check if batching is working correctly and actually saving us queries on the new landing page.

feat(perf): Add event to monitor batch queries on Landing v3

---

reload_app/events.py

This is a new event to track changes to the landing tabs in landing v3.

ref(perf): Track changing landingv3 tabs

---

reload_app/events.py

To see if users mistakenly click on the tag expecting something to happen because of the new design.
Corresponding PR: https://github.com/getsentry/sentry/pull/30763

feat(ui): Add click event for tags

---

reload_app/events.py

Stops sending analytics for discover queries from the discover results page
Sentry: https://github.com/getsentry/sentry/pull/33085
No longer using `discover_views.query` and `discover.query` doesn't seem to be in use

fix(discover): Removes events for tracking Discover Queries

---

reload_app/events.py

This adds parameters for 'new_alert_rule.viewed' analytics event.
Ref: https://github.com/getsentry/sentry/pull/34526

feat(alerts): Add parameters for duplicate rule analytics

---

reload_app/events.py

This adds the parameter `wizard_v3` to the `new_alert_rule.viewed` analytics events to see the usage of the Alert Wizard V3.

feat(alerts): Add analytics for alert wizard v3

---

reload_app/events.py

Adds instrumentation for the following events:
- Filter by operation dropdown
- Searchbar
- Click on a span to view its details
- Anchoring a span
- Click button to view JSON data of the event
- Switch the vital type from the dropdown
- Open in Discover
- Transaction clicked
Also adds an event for when a user views the Span Summary page, which I had forgotten to add earlier.

feat(perf): Add analytics events for transaction summary, vital detail, and trace view

---

reload_app/events.py

This PR passes a string containing the selected project platform(s) for each relevant pageview event within Performance. This data could be useful, since it would allow us to see different workflows within Performance depending on the type of project selected.
Adds this data to the following events:
- Landing Page view
- Trends Page view
- Transaction Summary Page view
- Transaction Summary Tab Views
- Span Summary Page View
- Event Details Page View
- Vital Detail Page View

feat(perf): Add selected project platforms to analytics events for Performance page views

---

reload_app/events.py

This adds an event for clicks on the usage log's filter drop down menu.
[getsentry/getsentry/#7741](https://github.com/getsentry/getsentry/pull/7741)

feat(subscription): Add usagelog filter clicked event

---

reload_app/events.py

We don't need an explicit schema for the `issue_details.viewed` event because it's the new style analytics that honors what the client sends even if the event isn't defined.

feat: remove issue_details.viewed from schema

---

.github/workflows/lint-pipelines.sh
.github/workflows/lint-pipelines.yml
gocd/pipelines/reload.yaml

This adds deployment configurations for GoCD, the new internal continuous deployment tool. Please refer to the [Freight Migration Guide](https://www.notion.so/sentry/Freight-Migration-Guide-2bd47bb683254077ad31e7ad625345ae) for info on how to coordinate GoCD deploys during this transitional phase.

cd: add GoCD deployment pipeline

---

reload_app/events.py

Since these events come from the new analytics event which doesn't require a reload schema, we can delete these events which are causing problems because `projects` is now a string instead of a list which didn't work well with Amplitude

fix: remove user feedback events

---

gocd/pipelines/reload.yaml

this pipeline's a bit old; we've since realized people would prefer to just one click deploy and not manually approve after checks

cd: automatically go to deploy

---

cloudbuild.yaml
gocd/pipelines/reload.yaml

in the others I've done a 3 stage rollout but I can't really do that here because I need to also move this from `internal-sentry` (private repos) to sentryio (public repos)
I've locked the deploy pipeline while making the switch and this repo gets ~0 commits so it should be fine during transition

move reload to google artifact registry

---

requirements.txt

apparently deps aren't frozen and this is broken:
```
File "./reload_app/wsgi.py", line 1, in <module>
from .app import make_app_from_environ
File "./reload_app/app.py", line 10, in <module>
from google.cloud import pubsub_v1
File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/__init__.py", line 18, in <module>
from google.cloud.pubsub_v1 import publisher
File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/publisher/__init__.py", line 17, in <module>
from google.cloud.pubsub_v1.publisher.client import Client
File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 22, in <module>
import six
ModuleNotFoundError: No module named 'six'
```

add missing dependency on six

---

reload_app/app.py
reload_app/tests.py

Error responses should have CORS headers so that we don't get warnings/errors in the javascript console on sentry.io

fix(cors) Add cors headers to error responses
